### ISSUE TITLE
可以考虑放到 A2OS 里维护

### ISSUE THREAD

**Issue by Triple-Z** [Kit4y/BookCorner#1]
个人觉得把资源集中起来受众面可能更广，有限的资源里能帮助到更多的同学。

还有一点其他的意见，DDL 还是应该设置一下的，否则很容易出现“霸书不还”的情况。

**Comment by Muyun99** [comment]
正在考虑同时借书上限为5本，霸书不还，名字永留github--kit4y

**Comment by Triple-Z** [comment]
> 
> 
> 正在考虑同时借书上限为5本，霸书不还，名字永留github--kit4y

你们这还一人多账号发言的嘛😂
